[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

[fmt]
# These are all the `forge fmt` defaults.
line_length = 130
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
